### ISSUE TITLE
Why do I get this error ?

### ISSUE THREAD

**Issue by Aztech-42** [Trenblack/Youtube_Viral_data_scraper#5]
Hello could someone explain why i get this error, I did everything that was needed (the three files are created).

Traceback (most recent call last):
  File "main.py", line 78, in <module>
    scraper.get_video_list()
  File "main.py", line 40, in get_video_list
    req = urllib.request.urlopen("https://www.googleapis.com/youtube/v3/playlistItems?part=snippet%2CcontentDetails&maxResults=50&playlistId="+ self.upid +"&key=" + key)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found


**Comment by Trenblack** [comment]
It looks like your API key is not valid. Make sure to create an account with the google developer thing.

**Comment by Aztech-42** [comment]
Well I created an account and than created an API key but it doesn't seem to solve the problem. Sorry.

**Comment by Aztech-42** [comment]
And what is weird is that it only works with the Buzzfeed data you provided.

**Comment by Trenblack** [comment]
Oh, you are probably incorrectly obtaining the user,id, upload_id parameters.

**Comment by Aztech-42** [comment]
How do I view it correctly then, thanks in advance !
